### ISSUE TITLE
ActorSystem has already shutdowned when session start.

### ISSUE THREAD

**Issue by takat0-h0rikosh1** [wvlet/airframe#1206]
I try to develop a application with akka-grpc, slick, airframe. Source code is [here](https://github.com/takat0-h0rikosh1/akka-gRPC-slick-playground).  

When I start the grpc server and make a request, the "ActorSystem" has already terminated and I get the following error.

```
java.lang.IllegalStateException: Cannot initialize ExecutionContext; AsyncExecutor already shut down
	at slick.util.AsyncExecutor$$anon$1.executionContext$lzycompute(AsyncExecutor.scala:69)
	at slick.util.AsyncExecutor$$anon$1.executionContext(AsyncExecutor.scala:67)
	at slick.util.AsyncExecutor$$anon$1.executionContext(AsyncExecutor.scala:51)
	at slick.jdbc.JdbcBackend$DatabaseDef.synchronousExecutionContext(JdbcBackend.scala:62)
	at slick.basic.BasicBackend$DatabaseDef.runSynchronousDatabaseAction(BasicBackend.scala:265)
	at slick.basic.BasicBackend$DatabaseDef.runSynchronousDatabaseAction$(BasicBackend.scala:263)
	at slick.jdbc.JdbcBackend$DatabaseDef.runSynchronousDatabaseAction(JdbcBackend.scala:37)
	at slick.basic.BasicBackend$DatabaseDef.slick$basic$BasicBackend$DatabaseDef$$runInContextInline(BasicBackend.scala:242)
	at slick.basic.BasicBackend$DatabaseDef.runInContextSafe(BasicBackend.scala:148)
	at slick.basic.BasicBackend$DatabaseDef.runInContext(BasicBackend.scala:142)
	at slick.basic.BasicBackend$DatabaseDef.runInContext$(BasicBackend.scala:141)
	at slick.jdbc.JdbcBackend$DatabaseDef.runInContext(JdbcBackend.scala:37)
	at slick.basic.BasicBackend$DatabaseDef.runInternal(BasicBackend.scala:77)
	at slick.basic.BasicBackend$DatabaseDef.runInternal$(BasicBackend.scala:76)
	at slick.jdbc.JdbcBackend$DatabaseDef.runInternal(JdbcBackend.scala:37)
	at slick.basic.BasicBackend$DatabaseDef.run(BasicBackend.scala:74)
	at slick.basic.BasicBackend$DatabaseDef.run$(BasicBackend.scala:74)
	at slick.jdbc.JdbcBackend$DatabaseDef.run(JdbcBackend.scala:37)
	at grpc.UserRepositoryImpl.getUser(Main.scala:58)
	at grpc.UserResolveService.getAll(Main.scala:49)
	at grpc.UserResolveService.getAll$(Main.scala:48)
	at grpc.userServiceComponent$$anon$3.getAll(Main.scala:42)
	at grpc.UserServiceImpl.getAll(UserServiceImpl.scala:17)
	at grpc.UserServiceImpl.getAll$(UserServiceImpl.scala:15)
	at grpc.grpcComponent$$anon$2.getAll(GRPCServer.scala:16)
	at myapp.proto.user.UserServiceHandler$.$anonfun$partial$2(UserServiceHandler.scala:95)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:56)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:93)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:93)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:48)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)
```

I guess that the ActorSystem has already quit when the session is started.
https://github.com/takat0-h0rikosh1/akka-gRPC-slick-playground/blob/master/src/main/scala/grpc/Main.scala#L35

In fact, if after line 35, writing "Thread.sleep()", It works as expected.

How should I do how to resolve the problem？

**Comment by xerial** [comment]
I haven't fully read your code, but how about using the tracer of Airframe DI to see the initialization and close timing of your comments? https://wvlet.org/airframe/docs/airframe#tracing-di-with-google-chrome-browser

I think this tracing will give us more ideas about what's happening.

**Comment by takat0-h0rikosh1** [comment]
> but how about using the tracer of Airframe DI to see the initialization and close timing of your components? https://wvlet.org/airframe/docs/airframe#tracing-di-with-google-chrome-browser

Ok, I will try it.

**Comment by takat0-h0rikosh1** [comment]
It resolved. if execute async process, It has to start gRPC server with `newSession`.
I fix like [that](https://github.com/takat0-h0rikosh1/akka-gRPC-slick-playground/commit/1cfb126e8e929384c7ea7759346e0d5c8fc605d7).

**Comment by xerial** [comment]
Good. But make sure closing the created session somewhere (e.g., when terminating Akka)
