### ISSUE TITLE
airframe-surface: reflection error when reading Java enum compiled with JDK11 with JDK8

### ISSUE THREAD

**Issue by xerial** [wvlet/airframe#1303]
```
java.lang.AssertionError: unsafe symbol PartitionType (child of package metadata) in runtime reflection universe
	at scala.reflect.internal.Symbols$Symbol.<init>(Symbols.scala:231)
	at scala.reflect.internal.Symbols$TypeSymbol.<init>(Symbols.scala:3093)
	at scala.reflect.internal.Symbols$ClassSymbol.<init>(Symbols.scala:3279)
	at scala.reflect.internal.Symbols$StubClassSymbol.<init>(Symbols.scala:3550)
```

**Comment by xerial** [comment]
It seems this happens when scanning Java classes compiled with JDK11 with JDK8.

**Comment by xerial** [comment]
We need to use consistent JDK versions as in regular Java applications
