### ISSUE TITLE
java.lang.NoClassDefFoundError: org/komamitsu/fluency/treasuredata/FluencyBuilderForTreasureData

### ISSUE THREAD

**Issue by takezoe** [wvlet/airframe#1400]
I got the following error with airframe-fluentd 20.12.1.
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/komamitsu/fluency/treasuredata/FluencyBuilderForTreasureData
        at wvlet.airframe.fluentd.Fluentd$.newFluentdLogger(Fluentd.scala:144)
        at wvlet.airframe.fluentd.package$.$anonfun$withFluentdLogger$1(package.scala:60)
        at wvlet.airframe.LazyF0.eval(LazyF0.scala:56)
        at wvlet.airframe.Binder$DependencyFactory.create(Binder.scala:79)
        at wvlet.airframe.AirframeSession.buildWithProvider$1(AirframeSession.scala:338)
        at wvlet.airframe.AirframeSession.$anonfun$getInstance$6(AirframeSession.scala:341)
        ...
```
Perhaps, https://github.com/wvlet/airframe/pull/1190 made fluency-treasuredata required even if we don't use TDLogger?

**Comment by xerial** [comment]
@takezoe If we don't use Airframe DI, #1190 is safe to use even without fluency-treasuredata dependency. When DI tries to initialize FluencyConfig, it might check all referenced classes from it. So I think this is an unexpected behavior of Surface module used inside DI. A workaround is actually importing fluency-treasuredata as a dependency of airframe-fluentd #1404

**Comment by takezoe** [comment]
Ah, I see. That could be the case. Thanks for taking look at this quickly!
