### ISSUE TITLE
airframe-surface: ReflectSurfaceFactory.ofClass(cl) causes illegal multithreaded access to ContextBase error in Scala 3

### ISSUE THREAD

**Issue by xerial** [wvlet/airframe#1698]
PrimitiveCodecTest shows this error https://github.com/lampepfl/dotty/blob/3.0.0/compiler/src/dotty/tools/dotc/core/Contexts.scala#L967:
```scala
 - find the actual codec for Any case objects 3.17ms << error: assertion failed: illegal multithreaded access to ContextBase

java.lang.AssertionError: assertion failed: illegal multithreaded access to ContextBase
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
	at dotty.tools.dotc.core.Contexts$ContextState.checkSingleThreaded(Contexts.scala:967)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:182)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:67)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:230)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:172)
	at scala.quoted.staging.QuoteCompiler$ExprRun.compileExpr(QuoteCompiler.scala:117)
	at scala.quoted.staging.QuoteDriver.run(QuoteDriver.scala:39)
	at scala.quoted.staging.Compiler$$anon$1.run(Compiler.scala:38)
	at scala.quoted.staging.package$.run(staging.scala:19)
	at wvlet.airframe.surface.reflect.TastySurfaceFactory$.ofClass$$anonfun$1(TastySurfaceFactory.scala:33)
	at scala.collection.concurrent.Map.getOrElseUpdate(Map.scala:99)
	at scala.collection.concurrent.Map.getOrElseUpdate$(Map.scala:96)
	at scala.collection.convert.JavaCollectionWrappers$JConcurrentMapWrapper.getOrElseUpdate(JavaCollectionWrappers.scala:411)
	at wvlet.airframe.surface.reflect.TastySurfaceFactory$.ofClass(TastySurfaceFactory.scala:34)
	at wvlet.airframe.surface.reflect.ReflectSurfaceFactory$.ofClass(ReflectSurfaceFactory.scala:20)
```

**Comment by xerial** [comment]
An idea is stop using ConcurrentHashMap for caching already created Surface instances.

**Comment by exoego** [comment]
This workaround suppresses "illegal multithreaded access" error.
https://github.com/wvlet/airframe/pull/2147/commits/f9080618d14489f7cdfde503a0a399b1c4c780ba

Then, actual error is shown
```
 - find the actual codec for Any case objects 21.69ms << error: NoType (of class dotty.tools.dotc.core.Types$NoType$)
```

**Comment by xerial** [comment]
Nice catch!

**Comment by xerial** [comment]
A workaround of this problem is passing known codecs when building AnyCodec https://github.com/wvlet/airframe/pull/2211 With this change, codec tests have passed. 

This fix might be necessary when migrating airframe-http-codegen module to Scala 3

**Comment by xerial** [comment]
Deprioritize this work because it will not be required if we support https://github.com/wvlet/airframe/issues/2667
