### ISSUE TITLE
airframe-sql: Unable to parse statement referencing table named "table"

### ISSUE THREAD

**Issue by jmaness** [wvlet/airframe#2536]
The statement `SELECT id FROM table` cannot be successfully parsed, and the error message below is returned. If the table is not named `table`, the SQL is successfully parsed. However, an example of where the table name is named `table` is https://developer.domo.com/docs/dataset-api-reference/dataset#Query%20a%20DataSet

```
scala> wvlet.airframe.sql.parser.SQLParser.parse("SELECT id FROM table")
wvlet.airframe.sql.SQLError: [SyntaxError] Parse error at line:1, pos:15. mismatched input 'table' expecting {'(', 'ADD', 'ALL', 'ANALYZE', 'ANY', 'ARRAY', 'ASC', 'AT', 'BERNOULLI', 'CALL', 'CASCADE', 'CATALOGS', 'COLUMN', 'COLUMNS', 'COMMENT', 'COMMIT', 'COMMITTED', 'CURRENT', 'DATA', 'DATE', 'DAY', 'DESC', 'DISTRIBUTED', 'EXCLUDING', 'EXPLAIN', 'FILTER', 'FIRST', 'FOLLOWING', 'FORMAT', 'FUNCTIONS', 'GRANT', 'GRANTS', 'GRAPHVIZ', 'HOUR', 'IF', 'INCLUDING', 'INPUT', 'INTERVAL', 'ISOLATION', 'LAST', 'LATERAL', 'LEVEL', 'LIMIT', 'LOGICAL', 'MAP', 'MINUTE', 'MONTH', 'NFC', 'NFD', 'NFKC', 'NFKD', 'NO', 'NULLIF', 'NULLS', 'ONLY', 'OPTION', 'ORDINALITY', 'OUTPUT', 'OVER', 'PARTITION', 'PARTITIONS', 'POSITION', 'PRECEDING', 'PRIVILEGES', 'PROPERTIES', 'PUBLIC', 'RANGE', 'READ', 'RENAME', 'REPEATABLE', 'REPLACE', 'RESET', 'RESTRICT', 'REVOKE', 'ROLLBACK', 'ROW', 'ROWS', 'SCHEMA', 'SCHEMAS', 'SECOND', 'SERIALIZABLE', 'SESSION', 'SET', 'SETS', 'SHOW', 'SOME', 'START', 'STATS', 'SUBSTRING', 'SYSTEM', 'TABLES', 'TABLESAMPLE', 'TEXT', 'TIME', 'TIMESTAMP', 'TO', 'TRANSACTION', 'TRY_CAST', 'TYPE', 'UNBOUNDED', 'UNCOMMITTED', 'UNNEST', 'USE', 'VALIDATE', 'VERBOSE', 'VIEW', 'WORK', 'WRITE', 'YEAR', 'ZONE', IDENTIFIER, DIGIT_IDENTIFIER, QUOTED_IDENTIFIER, BACKQUOTED_IDENTIFIER}
  at wvlet.airframe.sql.SQLErrorCode$SQLErrorBuilder.newException(SQLError.scala:56)
  at wvlet.airframe.sql.parser.SQLParser$$anon$1.syntaxError(SQLParser.scala:38)
  at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
  at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
  at org.antlr.v4.runtime.DefaultErrorStrategy.reportInputMismatch(DefaultErrorStrategy.java:327)
  at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:139)
  at wvlet.airframe.sql.parser.SqlBaseParser.relationPrimary(SqlBaseParser.java:5504)
  at wvlet.airframe.sql.parser.SqlBaseParser.aliasedRelation(SqlBaseParser.java:5171)
  at wvlet.airframe.sql.parser.SqlBaseParser.relation(SqlBaseParser.java:4775)
  at wvlet.airframe.sql.parser.SqlBaseParser.querySpecification(SqlBaseParser.java:4036)
  at wvlet.airframe.sql.parser.SqlBaseParser.queryPrimary(SqlBaseParser.java:3775)
  at wvlet.airframe.sql.parser.SqlBaseParser.queryTerm(SqlBaseParser.java:3575)
  at wvlet.airframe.sql.parser.SqlBaseParser.queryNoWith(SqlBaseParser.java:3423)
  at wvlet.airframe.sql.parser.SqlBaseParser.query(SqlBaseParser.java:2849)
  at wvlet.airframe.sql.parser.SqlBaseParser.statement(SqlBaseParser.java:1477)
  at wvlet.airframe.sql.parser.SqlBaseParser.singleStatement(SqlBaseParser.java:245)
  at wvlet.airframe.sql.parser.SQLParser$.parse(SQLParser.scala:59)
  ... 36 elided
Caused by: org.antlr.v4.runtime.InputMismatchException
  at org.antlr.v4.runtime.DefaultErrorStrategy.sync(DefaultErrorStrategy.java:270)
  at wvlet.airframe.sql.parser.SqlBaseParser.relationPrimary(SqlBaseParser.java:5410)
  ... 46 more
```

**Comment by xerial** [comment]
table is a reserved word. How about using double quote? For example, `select id from "table"`?

**Comment by jmaness** [comment]
Thanks, that does appear to work. I realized from looking at the source code that the dialect currently supported by `airframe-sql` is for Presto, and I found https://prestodb.io/docs/current/language/reserved.html that confirmed that `table` is a reserved keyword.

Are custom dialects possibly a roadmap feature?

**Comment by xerial** [comment]
I think we don't add dialect support when reading SQL queries because airframe-sql is intended to provide a unified SQL access interface. Having variations here is not ideal. A potential change is upgrading the grammar to be consistent with Trino. 

For output, it's planned to support various outputs in Presto/Trino/Hive syntax.
