### ISSUE TITLE
Design serialization failure at Scala 2.13.0-RC1 preview

### ISSUE THREAD

**Issue by xerial** [wvlet/airframe#476]
Reported in https://github.com/scala/bug/issues/11453

```
community-builds> version=2.13.0-pre-59975bb ./run.sh airframe
```
```
[airframe] [info] Design
[airframe] [info] - should be serializable *** FAILED ***
[airframe] [info]   java.lang.ClassCastException: cannot assign instance of scala.collection.generic.DefaultSerializationProxy to field wvlet.airframe.Design.binding of type scala.collection.immutable.Vector in instance of wvlet.airframe.Design
[airframe] [info]   at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2287)
[airframe] [info]   at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1417)
[airframe] [info]   at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2293)
[airframe] [info]   at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
[airframe] [info]   at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
[airframe] [info]   at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
[airframe] [info]   at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
[airframe] [info]   at wvlet.airframe.DesignSerializationTest$.deserialize(DesignSerializationTest.scala:34)
[airframe] [info]   at wvlet.airframe.DesignSerializationTest.$anonfun$new$2(DesignSerializationTest.scala:48)
[airframe] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[airframe] [info]   ...
[airframe] [info] - should serialize instance binding *** FAILED ***
[airframe] [info]   java.lang.ClassCastException: cannot assign instance of scala.collection.generic.DefaultSerializationProxy to field wvlet.airframe.Design.binding of type scala.collection.immutable.Vector in instance of wvlet.airframe.Design
[airframe] [info]   at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2287)
[airframe] [info]   at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1417)
[airframe] [info]   at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2293)
[airframe] [info]   at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
[airframe] [info]   at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
[airframe] [info]   at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
[airframe] [info]   at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
[airframe] [info]   at wvlet.airframe.DesignSerializationTest$.deserialize(DesignSerializationTest.scala:34)
[airframe] [info]   at wvlet.airframe.DesignSerializationTest.$anonfun$new$3(DesignSerializationTest.scala:55)
[airframe] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[airframe] [info]   ...
[airframe] [info] ProviderRefTest:
[airframe] [info] Airframe
[airframe] [info] - should build object from instance provider ref
[airframe] [info] - should eagerly build singleton from provider
[airframe] [info] - should bind singletons
[airframe] [info] - should bind singleton with provider
[airframe] [info] BindFactory:
[airframe] [info] BindFactory
[airframe:error] 2019-03-29 15:40:42.468-0700  info [BindFactory$XY] Hi World!  - (BindFactory.scala:37)
[airframe:error] 2019-03-29 15:40:42.476-0700  info [BindFactory$Z] Hello Scala!  - (BindFactory.scala:53)
[airframe:error] 2019-03-29 15:40:42.477-0700  info [BindFactory$Z] Good-bye Scala!  - (BindFactory.scala:59)
[airframe:error] 2019-03-29 15:40:42.477-0700  info [BindFactory$XY] Bye World!  - (BindFactory.scala:43)
[airframe] [info] - should run
[airframe] [info] HigherKindTypeTest:
[airframe] [info] Airframe
[airframe] [info] - should support higher kind types
[airframe] [info] ProviderSerializationTest:
[airframe] [info] Design
[airframe] [info] - should serialize design with provider *** FAILED ***
[airframe] [info]   java.lang.ClassCastException: cannot assign instance of scala.collection.generic.DefaultSerializationProxy to field wvlet.airframe.Design.binding of type scala.collection.immutable.Vector in instance of wvlet.airframe.Design
[airframe] [info]   at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2287)
[airframe] [info]   at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1417)
[airframe] [info]   at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2293)
[airframe] [info]   at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
[airframe] [info]   at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
[airframe] [info]   at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
[airframe] [info]   at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
[airframe] [info]   at wvlet.airframe.DesignSerializationTest$.deserialize(DesignSerializationTest.scala:34)
[airframe] [info]   at wvlet.airframe.ProviderSerializationTest.$anonfun$new$2(ProviderSerializationTest.scala:31)
[airframe] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[airframe] [info]   ...
[airframe] [info] - should serialize design with provider1 *** FAILED ***
[airframe] [info]   java.lang.ClassCastException: cannot assign instance of scala.collection.generic.DefaultSerializationProxy to field wvlet.airframe.Design.binding of type scala.collection.immutable.Vector in instance of wvlet.airframe.Design
[airframe] [info]   at java.io.ObjectStreamClass$FieldReflector.setObjFieldValues(ObjectStreamClass.java:2287)
[airframe] [info]   at java.io.ObjectStreamClass.setObjFieldValues(ObjectStreamClass.java:1417)
[airframe] [info]   at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2293)
[airframe] [info]   at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2211)
[airframe] [info]   at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
[airframe] [info]   at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
[airframe] [info]   at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
[airframe] [info]   at wvlet.airframe.DesignSerializationTest$.deserialize(DesignSerializationTest.scala:34)
[airframe] [info]   at wvlet.airframe.ProviderSerializationTest.$anonfun$new$5(ProviderSerializationTest.scala:42)
[airframe] [info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[airframe] [info]   ...
```

**Comment by xerial** [comment]
Probably fixed in #478, but not 100% sure for that

**Comment by xerial** [comment]
Related to https://github.com/scala/scala/pull/7624.

We may need to use custom serializer

**Comment by xerial** [comment]
Resolved for now by forking JVM at airframe test #479
