### ISSUE TITLE
airspec: NoClassDef error for the empty task project

### ISSUE THREAD

**Issue by xerial** [wvlet/airframe#612]
```
[error] java.lang.NoClassDefFoundError: scala/reflect/api/Trees$TreeApi
[error] 	at wvlet.airspec.runner.AirSpecLogger.<init>(AirSpecLogger.scala:42)
[error] 	at wvlet.airspec.runner.AirSpecRunner.<init>(AirSpecRunner.scala:28)
[error] 	at wvlet.airspec.runner.AirSpecRunner$.newRunner(AirSpecRunner.scala:57)
[error] 	at wvlet.airspec.Framework.runner(Framework.scala:29)
[error] 	at sbt.Defaults$.$anonfun$createTestRunners$1(Defaults.scala:1035)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
[error] 	at scala.collection.immutable.Map$Map1.foreach(Map.scala:128)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at sbt.Defaults$.createTestRunners(Defaults.scala:1029)
[error] 	at sbt.Defaults$.allTestGroupsTask(Defaults.scala:1097)
[error] 	at sbt.Defaults$.$anonfun$testTasks$10(Defaults.scala:834)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:289)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] Caused by: java.lang.ClassNotFoundException: scala.reflect.api.Trees$TreeApi
[error] 	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
[error] 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
[error] 	at wvlet.airspec.runner.AirSpecLogger.<init>(AirSpecLogger.scala:42)
[error] 	at wvlet.airspec.runner.AirSpecRunner.<init>(AirSpecRunner.scala:28)
[error] 	at wvlet.airspec.runner.AirSpecRunner$.newRunner(AirSpecRunner.scala:57)
[error] 	at wvlet.airspec.Framework.runner(Framework.scala:29)
[error] 	at sbt.Defaults$.$anonfun$createTestRunners$1(Defaults.scala:1035)
[error] 	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:237)
[error] 	at scala.collection.immutable.Map$Map1.foreach(Map.scala:128)
[error] 	at scala.collection.TraversableLike.map(TraversableLike.scala:237)
[error] 	at scala.collection.TraversableLike.map$(TraversableLike.scala:230)
[error] 	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
[error] 	at sbt.Defaults$.createTestRunners(Defaults.scala:1029)
[error] 	at sbt.Defaults$.allTestGroupsTask(Defaults.scala:1097)
[error] 	at sbt.Defaults$.$anonfun$testTasks$10(Defaults.scala:834)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:280)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:289)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:280)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error] 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error] 	at java.base/java.lang.Thread.run(Thread.java:834)
[error] (Test / executeTests) java.lang.NoClassDefFoundError: scala/reflect/api/Trees$TreeApi```

**Comment by xerial** [comment]
Fixed in #612
