### ISSUE TITLE
Exception thrown at shutdown hooks

### ISSUE THREAD

**Issue by xerial** [wvlet/airframe#658]
It looks like multiple shutdown hooks were running during the JVM shutdown:
```
Exception in thread "shutdownHook15" java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
	at java.lang.Runtime.removeShutdownHook(Runtime.java:239)
	at scala.sys.ShutdownHookThread.remove(ShutdownHookThread.scala:23)
	at wvlet.airframe.lifecycle.AddShutdownHook$.$anonfun$removeShutdownHooksFor$1(AddShutdownHook.scala:34)
	at scala.Option.map(Option.scala:163)
	at wvlet.airframe.lifecycle.AddShutdownHook$.removeShutdownHooksFor(AddShutdownHook.scala:30)
	at wvlet.airframe.lifecycle.AddShutdownHook$.$anonfun$beforeStart$1(AddShutdownHook.scala:45)
	at scala.sys.ShutdownHookThread$$anon$1.run(ShutdownHookThread.scala:37)
Exception in thread "shutdownHook18" java.lang.IllegalStateException: Shutdown in progress
	at java.lang.ApplicationShutdownHooks.remove(ApplicationShutdownHooks.java:82)
	at java.lang.Runtime.removeShutdownHook(Runtime.java:239)
	at scala.sys.ShutdownHookThread.remove(ShutdownHookThread.scala:23)
	at wvlet.airframe.lifecycle.AddShutdownHook$.$anonfun$removeShutdownHooksFor$1(AddShutdownHook.scala:34)
	at scala.Option.map(Option.scala:163)
	at wvlet.airframe.lifecycle.AddShutdownHook$.removeShutdownHooksFor(AddShutdownHook.scala:30)
	at wvlet.airframe.lifecycle.AddShutdownHook$.$anonfun$beforeStart$1(AddShutdownHook.scala:45)
	at scala.sys.ShutdownHookThread$$anon$1.run(ShutdownHookThread.scala:37)```

**Comment by xerial** [comment]
This error happens after running airframeJVM/test and exittng sbt.
