### ISSUE TITLE
Design.showConfig throws java.lang.NoSuchFieldException: port

### ISSUE THREAD

**Issue by takezoe** [wvlet/airframe#901]
```
[info]   java.lang.NoSuchFieldException: port
[info]   at java.lang.Class.getDeclaredField(Class.java:2070)
[info]   at wvlet.airframe.surface.reflect.RuntimeMethodParameter.field$lzycompute(RuntimeMethodParameter.scala:33)
[info]   at wvlet.airframe.surface.reflect.RuntimeMethodParameter.field(RuntimeMethodParameter.scala:33)
[info]   at wvlet.airframe.surface.reflect.RuntimeMethodParameter.get(RuntimeMethodParameter.scala:37)
[info]   at wvlet.airframe.config.Config.$anonfun$printConfig$3(Config.scala:102)
[info]   at scala.collection.Iterator.foreach(Iterator.scala:941)
[info]   at scala.collection.Iterator.foreach$(Iterator.scala:941)
[info]   at scala.collection.AbstractIterator.foreach(Iterator.scala:1429)
[info]   at scala.collection.IterableLike.foreach(IterableLike.scala:74)
[info]   at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
[info]   ...
```
Looks like the root cause is https://github.com/wvlet/airframe/pull/858 since this change includes making `DBConfig.port` private.

**Comment by takezoe** [comment]
@xerial Added a test case which can reproduce this issue at: https://github.com/wvlet/airframe/pull/902 and wrote possible options there. Could you take a look?

**Comment by xerial** [comment]
FYI

```
$ javap -p airframe-config/target/scala-2.12/test-classes/wvlet/airframe/config/AirframeBootstrapTest\$DBConfig.class
Compiled from "AirframeBootstrapTest.scala"
public class wvlet.airframe.config.AirframeBootstrapTest$DBConfig implements scala.Product,scala.Serializable {
  private final java.lang.String host;
  private final scala.Option<java.lang.Object> wvlet$airframe$config$AirframeBootstrapTest$DBConfig$$port;  <<--- special field name is used if the default value is defined
  public scala.Option<java.lang.Object> port$access$1();
  public java.lang.String host();
  public scala.Option<java.lang.Object> wvlet$airframe$config$AirframeBootstrapTest$DBConfig$$port();
  public wvlet.airframe.config.AirframeBootstrapTest$DBConfig copy(java.lang.String, scala.Option<java.lang.Object>);
  public java.lang.String copy$default$1();
  public scala.Option<java.lang.Object> copy$default$2();
  public java.lang.String productPrefix();
  public int productArity();
  public java.lang.Object productElement(int);
  public scala.collection.Iterator<java.lang.Object> productIterator();
  public boolean canEqual(java.lang.Object);
  public int hashCode();
  public java.lang.String toString();
  public boolean equals(java.lang.Object);
  public wvlet.airframe.config.AirframeBootstrapTest$DBConfig(java.lang.String, scala.Option<java.lang.Object>);
}
```
